### ISSUE TITLE
Bot doesn't play songs in queue

### ISSUE THREAD

**Issue by pewpasta** [JapanPanda/sheesh-bot#1] opened 2021-08-29 04:15 UTC
After a song has finished playing a song, it still remains in the queue and the bot doesn't play the songs next in queue. The skip command doesn't work at this point.
However, the skip command does work when it's used while the song is playing.

**Comment by JapanPanda** [comment] 2021-08-29 04:55
Thanks for bringing this issue up. It sounds like a big issue, but it seems to be working fine on the official Aqua Bot instance however ([Invite Link](https://discord.com/api/oauth2/authorize?client_id=837918347772952576&permissions=36773952&scope=bot)).

To help me debug this, could you answer the following:
1. Are you trying to host this bot locally? If so, are you getting any error messages?
2. Can you provide the steps (and commands including the song link, settings, and etc) to reproduce?

**Comment by pewpasta** [comment] 2021-08-31 03:46
I was trying to run the bot on [replit](https://replit.com/@burg2/aqua-bot). I was using [my fork of this repo](https://github.com/pewpasta/aqua-bot) where I 

1. added ffmpeg to package.json and updated the ytdl version
2. removed the sodium package from package.json as it was giving errors while installing and wasn't being used anywhere in the code
3. added a password env variable for the redis server in redis.js
4. made a minor fix in now.js where the bot didn't send the error message if a link or keyword was not specified in the now command
The issue was not song specific and occured for all songs.
![sji8DTVGyO](https://user-images.githubusercontent.com/67459484/131438062-da01720b-cbb8-42af-8085-dc54a7dde5ae.png)

However it turns out that the bot works fine if I run it locally. So the problem must be with replit,I guess. It's still kinda weird as I've run quite a lot of music bots on there before and this never happened before.


The bot still has trouble playing some specific playlists from Spotify [like this](https://open.spotify.com/playlist/5CSExtqMuZvpoqmMp2Bpt8) and [this](https://open.spotify.com/playlist/07WQk76RWdPv06pjYurxZ0)
(The official bot doesn't play these playlists either)

This is the error I get

> `error: Error while retrieving Spotify Playlist https://open.spotify.com/playlist/5CSExtqMuZvpoqmMp2Bpt8.
WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: Not found..
    at _toError (/home/runner/aqua-bot/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
    at /home/runner/aqua-bot/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/home/runner/aqua-bot/node_modules/superagent/lib/node/index.js:905:3)
    at /home/runner/aqua-bot/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/home/runner/aqua-bot/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (events.js:314:20)
    at Unzip.<anonymous> (/home/runner/aqua-bot/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {"timestamp":"2021-08-31 03:41:27"}
(node:84) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tracks' of null
    at AudioPlayer.queueSpotifyPlaylist (/home/runner/aqua-bot/modules/audioPlayer.js:559:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:84) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by JapanPanda** [comment] 2021-08-31 04:15
Thanks for the followup and detailed message.

For the repl.it issue, I don't think I will spend effort fixing it merely because it's not meant to be run on repl.it. Sorry about that.

As for the Spotify playlists, I'll look into it. I can tell already that the first [playlist](https://open.spotify.com/playlist/5CSExtqMuZvpoqmMp2Bpt8) you sent me does not resolve if I were to open it through my web-browser. I suspect this is a private/unlisted Spotify playlist?

The bot doesn't support non-public playlists since it has no way of accessing non-public playlists. I should probably make it throw an error in that case.

As for the other playlist, it resolves; so I'll be looking into that. The interesting thing is that it doesn't have an embed on Discord when you link it, so something must be funky with this playlist as well.

![](https://i.imgur.com/E6tYi1U.png)

**Comment by JapanPanda** [comment] 2021-08-31 06:18
Added a fix for this. Did it solve your problem?

The issues were:
1) First playlist wasn't public
2) Second playlist had some weird null tracks being returned from Spotify. Not too sure why Spotify API returned some null tracks, but it should be fixed now with a simple check.

**Comment by pewpasta** [comment] 2021-09-04 04:22
Yeah, my bad. I didn't see that the first playlist was private.
And about the replit part, I was getting errors because replit's default node version is v12.22.1 which does not support discord.js v13 so it used v12 instead. Later, I did manage to get it working fine on replit by upgrading node and running it from the shell instead of the console.
Sorry for the late response !

**Comment by JapanPanda** [comment] 2021-09-04 04:35
No worries! Thanks for submitting an issue, please feel free to submit some more (or even submit PRs with new features/bug fixes lol).

**Closed as completed by JapanPanda** 2021-09-04 04:35 UTC
Labels: bug
